name: Prod Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Configure AWS Credentials for Production
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TOOLS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TOOLS }}
          aws-region: us-west-2
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: ProductionDeploymentSession
      - run: sam build --use-container

      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --role-arn ${{ env.AWS_ROLE_TO_ASSUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
